import { ResearchSource } from "./research-types";

export const RESEARCH_SOURCES: ResearchSource[] = [
  {
    id: "bare-acts",
    name: "India Code",
    category: "Bare Acts",
    description: "Official Indian statutes and amendments",
    officialUrl: "https://www.indiacode.nic.in/",
    accessType: "free",
    sourceType: "bare-act",
    enabled: true,
  },
  {
    id: "case-law-scc",
    name: "SCC Online",
    category: "Case Law",
    description: "Supreme Court cases and judgments",
    officialUrl: "https://scc.gov.in/",
    accessType: "subscription",
    sourceType: "case-law",
    enabled: false,
  },
  {
    id: "commentary-indlaw",
    name: "Indian Law Journal",
    category: "Commentary",
    description: "Scholarly articles on Indian law",
    officialUrl: "https://indianlawjournal.com/",
    accessType: "free",
    sourceType: "commentary",
    enabled: true,
  },
  {
    id: "academic-helsinki",
    name: "Helsinki University Law Repository",
    category: "Academic",
    description: "Legal research papers and theses",
    officialUrl: "https://research.helsinki.fi/",
    accessType: "free",
    sourceType: "academic",
    enabled: true,
  },
  {
    id: "specialized-tax",
    name: "Taxmann",
    category: "Specialized",
    description: "Tax law resources and commentary",
    officialUrl: "https://taxmann.com/",
    accessType: "subscription",
    sourceType: "specialized",
    enabled: false,
  },
];
