/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasedeskRouteImport } from './routes/casedesk'
import { Route as CauselistRouteImport } from './routes/causelist'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ResearchRouteImport } from './routes/research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasedeskRoute = CasedeskRouteImport.update({
  id: '/casedesk',
  path: '/casedesk',
  getParentRoute: () => rootRouteImport,
} as any)
const CauselistRoute = CauselistRouteImport.update({
  id: '/causelist',
  path: '/causelist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casedesk': typeof CasedeskRoute
  '/causelist': typeof CauselistRoute
  '/registry': typeof RegistryRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casedesk': typeof CasedeskRoute
  '/causelist': typeof CauselistRoute
  '/registry': typeof RegistryRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casedesk': typeof CasedeskRoute
  '/causelist': typeof CauselistRoute
  '/registry': typeof RegistryRoute
  '/research': typeof ResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/casedesk' | '/causelist' | '/registry' | '/research'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/casedesk' | '/causelist' | '/registry' | '/research'
  id: '__root__' | '/' | '/casedesk' | '/causelist' | '/registry' | '/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasedeskRoute: typeof CasedeskRoute
  CauselistRoute: typeof CauselistRoute
  RegistryRoute: typeof RegistryRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casedesk': {
      id: '/casedesk'
      path: '/casedesk'
      fullPath: '/casedesk'
      preLoaderRoute: typeof CasedeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causelist': {
      id: '/causelist'
      path: '/causelist'
      fullPath: '/causelist'
      preLoaderRoute: typeof CauselistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasedeskRoute: CasedeskRoute,
  CauselistRoute: CauselistRoute,
  RegistryRoute: RegistryRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
